name: shop_ease
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.6.1

#----------------- packages -----------------#
dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8



  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.13.0

  #State Management
  get: ^4.7.2
  get_storage: ^2.1.1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1
  path: ^1.9.1
  cloudinary_public: ^0.23.1
  cloudinary_flutter: ^1.3.0


#----------------- ./ PACKAGES End -----------------#
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true



  #----------------- LOCAL ASSETS -----------------#
  assets:
   - assets/logos/
   - assets/icons/brands/
   - assets/images/on_boarding_images/
   - assets/images/animations/
   - assets/icons/categories/
   - assets/icons/payment_methods/
   - assets/images/banners/
   - assets/images/products/
   - assets/images/user/
   - assets/images/reviews/
   - assets/data/products.json



   #----------------- LOCAL FONTS -----------------#

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 800
          - asset: assets/fonts/Poppins-Italic.ttf
            style: italic
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300
          - asset: assets/fonts/Poppins-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
            weight: 600
            style: italic


