// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Wd2ujhWFCCcnxcv1wyjzPuYrDwzifMM',
    appId: '1:117198644684:web:127ea6fd1e6c38bb9d2969',
    messagingSenderId: '117198644684',
    projectId: 'shopease-41e94',
    authDomain: 'shopease-41e94.firebaseapp.com',
    storageBucket: 'shopease-41e94.firebasestorage.app',
    measurementId: 'G-7Z36PHDQS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArbdl0ViudzQKKbk5xzQkFcpL-M-gp-sI',
    appId: '1:117198644684:android:527897dbe1a73a999d2969',
    messagingSenderId: '117198644684',
    projectId: 'shopease-41e94',
    storageBucket: 'shopease-41e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8PAZ9XSALzQ64-6qedjuJ9PKsToP_t48',
    appId: '1:117198644684:ios:55653f470093ca6c9d2969',
    messagingSenderId: '117198644684',
    projectId: 'shopease-41e94',
    storageBucket: 'shopease-41e94.firebasestorage.app',
    androidClientId: '117198644684-m8kbskm0r5l1k4fofait5qoas0jnao1g.apps.googleusercontent.com',
    iosClientId: '117198644684-57v05rch9hluhj6olmm4db7f5pbjcj5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8PAZ9XSALzQ64-6qedjuJ9PKsToP_t48',
    appId: '1:117198644684:ios:55653f470093ca6c9d2969',
    messagingSenderId: '117198644684',
    projectId: 'shopease-41e94',
    storageBucket: 'shopease-41e94.firebasestorage.app',
    androidClientId: '117198644684-m8kbskm0r5l1k4fofait5qoas0jnao1g.apps.googleusercontent.com',
    iosClientId: '117198644684-57v05rch9hluhj6olmm4db7f5pbjcj5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Wd2ujhWFCCcnxcv1wyjzPuYrDwzifMM',
    appId: '1:117198644684:web:20c8c41ef93ada7d9d2969',
    messagingSenderId: '117198644684',
    projectId: 'shopease-41e94',
    authDomain: 'shopease-41e94.firebaseapp.com',
    storageBucket: 'shopease-41e94.firebasestorage.app',
    measurementId: 'G-PBYDXF5VSG',
  );

}